### ISSUE TITLE
Improve Developer experience

### ISSUE THREAD

**Issue by anay-208** [anay-208/next-mongodb-api#1]
### Task List
```[tasklist]
- [ ] Accept a generic Type so it returns that type, for typescript autocomplete
- [ ] Remove exec logic
- [ ] limit and sort to be set as a third argument of the function like `find()`
```

**Comment by anay-208** [comment]
Completed already
